# IDENTITI
title:            SAID BAHTA

# CONTACT
email:            saidbahta@yahoo.co.id
github_username:  saidbahta
fb:               https://web.facebook.com/bahtasaid
blog:             https://saidbahta.wordpress.com
github:           https://github.com/saidbahta
description:      Membahas perspektif penulis tentang komputer dan web development
url:              "https://saidbahta.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:          "blog" # the subpath of your site, e.g. /blog

# PLUGIN
plugins:
  - jekyll-feed
  - jekyll-sitemap

# CONFIGURATION
markdown:         kramdown
highlighter:      rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink:        pretty

active:           livereload

comments:         true

collections:
  buku:
    output:       true
